#! /bin/bash
#
# Simple backup script for MySQL backup of a database.
# After the backup it uploads the SQL file to a WebDAV
# server.
#

DBNAME="db_name"
REMOTE=""

echo "MySQL backup started on `date +%F-%k:%M:%S`."

echo "MySQL backup in progress..."
/usr/bin/mysqldump --defaults-extra-file=$HOME/.my.cnf --single-transaction --quick --lock-tables=false $DBNAME > $HOME/$DBNAME_$(date +%F).sql

echo "MySQL backup uploading..."
curl --user $USR:$PSW -T $HOME/$DBNAME_$(date +%F).sql -o /dev/stdout $REMOTE
rm $HOME/$DBNAME_$(date +%F).sql

echo "MySQL backup finished on `date +%F-%k:%M:%S`."
