#! /bin/bash
#
# Simple backup script for MySQL backup of a database.
# After the backup it uploads the SQL file to a WebDAV
# server.
#
# Configuration:
#
# - $HOME/.my.cnf: insert MySQL client credentials. E.g.:
#
#      > [client]
#      > user = username
#      > password = password
#
#   Remember to 'chmod 600 $HOME/.my.cnf' after.
#
# - $HOME/.dbdumpbackup/config: insert WebDAV credentials:
#
#      > USR="username"
#      > PSW="password"
#      > DBNAME="database name"
#      > REMOTE="WebDAV server"
#
#   Remember to 'chmod 600 $HOME/.dbdumpbackup/config'
#

source $HOME/.dbdumpbackup/config

echo "MySQL backup started on `date +%F-%k:%M:%S`."

echo "MySQL backup in progress..."
/usr/bin/mysqldump --defaults-extra-file=$HOME/.my.cnf --single-transaction --quick --lock-tables=false $DBNAME > $HOME/$DBNAME_$(date +%F).sql

echo "MySQL backup uploading..."
curl --user $USR:$PSW -T $HOME/$DBNAME_$(date +%F).sql -o /dev/stdout $REMOTE
rm $HOME/$DBNAME_$(date +%F).sql

unset USR PSW DBNAME REMOTE

echo "MySQL backup finished on `date +%F-%k:%M:%S`."
